### ISSUE TITLE
file_get_contents(https://chromedriver.storage.googleapis.com/2.39/notes.txt) Fails

### ISSUE THREAD

**Issue by danieltjewett** [staudenmeir/dusk-updater#2]
We've been using this updater now for a few months and has been great!  This morning, we've ran into this issue where it is not finding a notes file on googleapis.com.  Below is the stack trace:

```
[2018-05-30 14:11:03] testing.ERROR: ErrorException: file_get_contents(https://chromedriver.storage.googleapis.com/2.39/notes.txt): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found
in /home/rof/src/github.com/rootinc/continuum/vendor/staudenmeir/dusk-updater/src/UpdateCommand.php:177
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', '/home/rof/src/g...', 177, Array)
#1 /home/rof/src/github.com/rootinc/continuum/vendor/staudenmeir/dusk-updater/src/UpdateCommand.php(177): file_get_contents('https://chromed...')
#2 /home/rof/src/github.com/rootinc/continuum/vendor/staudenmeir/dusk-updater/src/UpdateCommand.php(73): Staudenmeir\DuskUpdater\UpdateCommand->versions('2.39')
#3 [internal function]: Staudenmeir\DuskUpdater\UpdateCommand->handle()
#4 /home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#9 /home/rof/src/github.com/rootinc/continuum/vendor/symfony/console/Command/Command.php(251): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /home/rof/src/github.com/rootinc/continuum/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/rof/src/github.com/rootinc/continuum/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Staudenmeir\DuskUpdater\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/rof/src/github.com/rootinc/continuum/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/rof/src/github.com/rootinc/continuum/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}  
```

Any help on this would be great!

**Comment by staudenmeir** [comment]
Google didn't provide notes for 2.39, I'll try to contact them.

**Comment by danieltjewett** [comment]
Looks like the file is there now.  I think there still might be an issue where running a parameter of `2.38` or `2.37` was still pulling down `2.39` file.

**Comment by staudenmeir** [comment]
The updater always fetches the latest `notes.txt` because it contains the whole version history. I didn't consider a missing file...

**Comment by staudenmeir** [comment]
While I'm talking to a real user: Are you missing any features?

**Comment by danieltjewett** [comment]
As of now, the feature set is great!

Interestingly I ran into this yesterday evening: `Facebook\WebDriver\Exception\SessionNotCreatedException: session not created exception: Chrome version must be >= 66.0.3359.0` which is not related to the issue at hand, but might be related to the drivers not updating?  I was going to look into this more today, but thought I would bring it up before I start my googling.

**Comment by staudenmeir** [comment]
Doesn't the message mean that you have to update Chrome?

**Comment by danieltjewett** [comment]
Maybe?  Perhaps that means the the Chrome binary in dusk is out-of-date?  We're using Laravel 5.4 with Dusk 1.something.

Here is the full stack trace from Codeship:

```
1) Tests\Browser\LegalTest::it_checks_if_legal_works
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created exception: Chrome version must be >= 66.0.3359.0
(Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 4.15.0-1009-aws x86_64)

/home/rof/src/github.com/rootinc/continuum/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:154
/home/rof/src/github.com/rootinc/continuum/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:326
/home/rof/src/github.com/rootinc/continuum/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:126
/home/rof/src/github.com/rootinc/continuum/tests/DuskTestCase.php:44
/home/rof/src/github.com/rootinc/continuum/vendor/laravel/dusk/src/TestCase.php:209
/home/rof/src/github.com/rootinc/continuum/vendor/laravel/framework/src/Illuminate/Support/helpers.php:706
/home/rof/src/github.com/rootinc/continuum/vendor/laravel/dusk/src/TestCase.php:210
/home/rof/src/github.com/rootinc/continuum/vendor/laravel/dusk/src/TestCase.php:116
/home/rof/src/github.com/rootinc/continuum/vendor/laravel/dusk/src/TestCase.php:88
```

**Comment by staudenmeir** [comment]
Chrome itself doesn't come with Dusk.

**Comment by danieltjewett** [comment]
So perhaps Codeship's version is Chrome is out of date?

**Comment by staudenmeir** [comment]
It looks like that.
